### ISSUE TITLE
Oh no

### ISSUE THREAD

**Issue by Lypheo** [Kiyamou/VapourSynth-JincResize#1]
When I said “Unfinished, unusably slow. Don’t use.”, I meant it, lol. It still has a lot of problems, most notably that it’s completely useless because nnedi3 is both faster and produces higher quality upscales. On top of that, it doesn’t sample from a proper ellipse when resizing to a different aspect ratio but instead always uses a cirlce. Further, it doesn’t handle borders very well (ideally, the edges should either be extended or mirrored when sampling outside of the image. Instead, it currently just truncates the kernel). 
You might wanna port https://github.com/AviSynth/jinc-resize instead for a much more complete and much faster implementation.

**Comment by Kiyamou** [comment]
I'm sorry for my sloppy behavior.
I just want to improve the function of jinc resize. I modified a little more code based on your version, so I choose to create a new repository instead of pull request.
Thanks for your suggestions. I learn a lot. The version I released is in a hurry. To be honest, as a beginner, I want to release as soon as possible to encourage myself. Now I know I need to learn a lot of things.
Although nnedi3 is better, I still want to continue. I just want learn the knowledge of coding and image processing by modifing the plugin.
Thank you again.

**Comment by Lypheo** [comment]
No need to thank me or apologize lol, I wasn’t being entirely serious. I’m just surprised that someone would use my code which I had considered completely worthless. :p
If you wanna learn about resampling, I recommend reading https://github.com/mpv-player/mpv/blob/master/video/out/filter_kernels.c and imagemagick’s guides (and possibly zimg’s source code as well).

**Comment by Kiyamou** [comment]
I got it. I will read these code and modifing my code.
Best Wishes.

(I close the issue.)
